# Generated by Django 4.2.10 on 2026-02-16 23:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Professional"),
                        ],
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in MXN per month. 0 for free plans.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_venues",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of venues this plan allows.",
                    ),
                ),
                (
                    "max_events_per_month",
                    models.IntegerField(
                        default=10, help_text="Maximum events per month."
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict, help_text="Key features as JSON object."
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe product ID for this plan.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, help_text="Stripe customer ID.", max_length=255
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, help_text="Stripe subscription ID.", max_length=255
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("renewal_date", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        default="free",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
