# Generated by Django 4.2.10 on 2026-04-18 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("sources_processed", models.IntegerField(default=0)),
                ("events_created", models.IntegerField(default=0)),
                ("events_deduped", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="eventdraft",
            new_name="agents_even_status_eff4ff_idx",
            old_name="agents_eventdraft_status_conf_idx",
        ),
    ]
