# Generated by Django 4.2.10 on 2026-04-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_agentrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsource",
            name="crawl_interval_hours",
            field=models.PositiveIntegerField(
                default=24, help_text="Minimum hours between crawls for this source."
            ),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="error_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="eventsource",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
