# Generated by Django 4.2.10 on 2026-04-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_eventsource_robustness_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsource",
            name="venue",
        ),
    ]
