# Generated by Django 4.2.10 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_increase_venue_slug_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="category",
            field=models.CharField(
                choices=[
                    ("museum", "Museum"),
                    ("gallery", "Gallery"),
                    ("theater", "Theater"),
                    ("cinema", "Cinema"),
                    ("cafe", "Café"),
                    ("bar", "Bar"),
                    ("restaurant", "Restaurant"),
                    ("hotel_hostel", "Hotel/Hostel"),
                    ("cultural_center", "Cultural Center"),
                    ("library", "Library"),
                    ("market", "Market"),
                    ("public_space", "Public Space"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
