# Generated by Django 4.2.10 on 2026-02-16 23:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("performance", "Performance"),
                            ("workshop", "Workshop"),
                            ("conference", "Conference"),
                            ("festival", "Festival"),
                            ("cinema", "Cinema"),
                            ("music", "Music"),
                            ("theater", "Theater"),
                            ("dance", "Dance"),
                            ("art", "Art"),
                            ("literature", "Literature"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField()),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("registered_count", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price in MXN. 0 for free events.",
                        max_digits=10,
                    ),
                ),
                ("is_free", models.BooleanField(db_index=True, default=True)),
                ("registration_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "ordering": ["start_datetime"],
            },
        ),
    ]
